name: Sync to Pages

on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'rules/**'
  workflow_dispatch:

jobs:
  sync-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Sync main to gh-pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout gh-pages
          git merge main --no-edit
          git push origin gh-pages 