name: Sync to Pages

on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'rules/**'
  workflow_dispatch:

jobs:
  sync-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Sync main to gh-pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # 确保我们在main分支上
          git checkout main
          
          # 复制需要同步的文件到临时目录，保持目录结构
          mkdir -p /tmp/sync_files/docs
          cp -r config rules /tmp/sync_files/
          cp -r config rules /tmp/sync_files/docs/
          
          # 切换到gh-pages分支
          git checkout gh-pages
          
          # 删除旧文件并复制新文件，保持目录结构
          rm -rf config rules docs/config docs/rules
          cp -r /tmp/sync_files/* .
          
          # 添加更改
          git add config rules docs
          
          # 如果有更改则提交
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync: Update from main branch"
            git push origin gh-pages
          fi